### ISSUE TITLE
Adding terms in the Glossary

### ISSUE THREAD

**Issue by Smartmind12** [SiaFoundation/docs#13]
Currently very limited terms are mentioned in the Glossary. I propose to add the following terms in Glossary so that users/readers have simplicity to understand the terms much better:
1. Fragmentation
2. Uptime 
3. De-platforming
4. Cryptocurrency
5. Fiat Currency
6. Software suite
7. API 
8. Broadcasting 
9. Utility 
10. Tokens
11. BIP 39 
12. Biometric
13. Petabyte
14. Exabyte
15. Proof of Burn
16. Denominated
17. Autonomy
18. Redundancy
19. Trustlessly
20. Bandwidth
21. Revenue
22. RPC 
23. UI
24. IP address
25. ISP
26. DNS 
27. Non-custodial

**Comment by Smartmind12** [comment]
Kindly assign this issue to so that i can bring about the above implementation!

**Comment by n8maninger** [comment]
Start with these. The others are either straightforward or don't make sense for our docs. If you have a case for the others, I'm open to them.

- Uptime
- De-platforming
- Cryptocurrency
- Fiat Currency
- API
- Broadcasting
- Utility Token
- BIP 39
- Proof of Burn
- Redundancy
- Trustless
- Bandwidth
- Revenue
- RPC
- UI
- IP address
- ISP
- DNS
- Non-custodial

**Comment by oliver-sia** [comment]
Golden! Thank you for contribution to the glossarry

**Comment by Smartmind12** [comment]
> Golden! Thank you for contribution to the glossarry



> Golden! Thank you for contribution to the glossarry

Hey @oliver-sia can you reopen this issue since i am yet to make a PR so that the above terms can be added to the flossary!

**Comment by oliver-sia** [comment]
No worries, I did merge some onto the docs the other day and today, so please review my additions to the glossary. Rewording, remove/add and etc., and ill review your pr

**Comment by Smartmind12** [comment]
> No worries, I did merge some onto the docs the other day and today, so please review my additions to the glossary. Rewording, remove/add and etc., and ill review your pr @Smartmind12

Ohh I see...so the remaining ones i will add and then you can review the same!
