### ISSUE TITLE
Hosting on Sia Errors

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/docs#32]
https://github.com/SiaFoundation/docs/blob/cd07d844b069debf43edfb6a8c640d027b8b6c4f/hosting/about-hosting-on-sia.md

`Once you've been online for about twelve weeks, about half of the default contract length, your penalty disappears!`

If contacts are defaulted to 3 months, not 6... This is wrong.

Please double-check it.

`SiaStats has developed a [Host Monitor](https://siastats.info/hosts) which evaluates hosts on pricing relative to other hosts. It even regularly evaluates host performance by forming contracts with every host to test bandwidth and latency. SiaStats has great visualization for each host, making judging their metrics easier.`

It should be removed/updated. I know there is @mike76-dev grant that will be a solution, but this is otherwise outdated now.

**Comment by pcfreak30** [comment]
@skunk-ink Please check the 1st issue I mentioned, as I see no diff change on that.

Kudos.

**Comment by skunk-ink** [comment]
Yeah, it's fine. The recommended contract length in autopilot is 6 months, so the docs are correct.

**Comment by pcfreak30** [comment]
> Yeah, it's fine. The recommended contract length in autopilot is 6 months, so the docs are correct.

Recommended or default? B/C those should be the same, and the default is six weeks, not six months.
